[image]
baseHeight = 500
baseWidth = 2000
textTtf = "/Library/Fonts/Arial.ttf"
[openjtalk]
dict = "/usr/local/Cellar/open-jtalk/1.11/dic"

[readText]
filePath ="talk.txt"
[output]
directory ="out/"
fileNameHeadText=5

[voice]
hts = ["/usr/local/Cellar/open-jtalk/1.11/voice/mei/mei_normal.htsvoice", "/usr/local/Cellar/open-jtalk/1.11/voice/m100/nitech_jp_atr503_m001.htsvoice"]
rgb = [[0.5,0.0,0.0],[0,0,0]]
newLineReplacers = ["1.","2."]
image =["image/cat.jpg",""]